import MessageReactions from './MessageReactions';
import {AvatarArt,AvatarPicker,defaultAvatar} from './avatars';
import Recall from './Recall';
import { lazy, Suspense, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowLeft, ArrowUpRight, Bell, BellOff, Check, ChevronDown, ChevronRight, Compass, Copy, Crown, FileText, Gamepad2, Hash, Headphones, HeadphoneOff, Inbox, Menu, MessageCircle, Mic, MicOff, MoreHorizontal, Pin, Plus, Radio, Reply, Search, Send, Settings, Shield, Smile, Sparkles, Trash2, Users, Volume2, X, Zap, Pencil, LogOut } from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useVirtualizer } from '@tanstack/react-virtual';
import { people, useStore, type Message, type Person } from './store';
const ConnectedWorkspace = lazy(()=>import('./ConnectedWorkspace'));

function IconButton({label,children,onClick,active=false,className=''}:{label:string;children:ReactNode;onClick:()=>void;active?:boolean;className?:string}) {return <button type="button" title={label} aria-label={label} className={`icon-button ${active?'active':''} ${className}`} onClick={onClick}>{children}</button>;}
function Avatar({person,size=40,status=true}:{person:Person;size?:number;status?:boolean}) {return <span className="avatar" style={{width:size,height:size,background:`linear-gradient(145deg, ${person.color}33, ${person.color}08)`,color:person.color,borderColor:`${person.color}50`}}><AvatarArt id={person.id} avatar={person.avatar} size={size}/>{status&&<i className={`presence ${person.status}`}/>}</span>;}
function Mark({small=false}:{small?:boolean}) {return <span className={`vexa-mark ${small?'small':''}`}><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M5 8h10l5 11 5-11h10L20 34Z" fill="currentColor"/></svg></span>;}
function Modal({title,description,children,onClose}:{title:string;description?:string;children:ReactNode;onClose:()=>void}) {return <Dialog.Root open onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal"><div className="modal-top"><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><button className="icon-button" aria-label="Close dialog"><X size={20}/></button></Dialog.Close></div><Dialog.Description className="modal-description">{description??'Make this space your own.'}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
// Static deploys (GitHub Pages, Vercel) ship this bundle with no API/gateway behind them.
// Only offer the connected workspace when a backend is actually expected: local dev, or a
// build that explicitly opts in via VITE_ENABLE_CONNECT=1 (e.g. a deploy that bundles the API).
const CONNECT_AVAILABLE=import.meta.env.DEV||import.meta.env.VITE_ENABLE_CONNECT==='1';

export default function App() {
 const [connected,setConnected]=useState(false);
 const s=useStore();const [modal,setModal]=useState<string|null>(null);const [view,setView]=useState<'chat'|'voice'|'friends'>('chat');const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [showMembers,setShowMembers]=useState(true);const [showPins,setShowPins]=useState(false);const [mobileNav,setMobileNav]=useState(false);const [draft,setDraft]=useState('');const [reply,setReply]=useState<Message|null>(null);const [editing,setEditing]=useState<Message|null>(null);const [muted,setMuted]=useState(false);const [deafened,setDeafened]=useState(false);const [notifications,setNotifications]=useState(true);const [toast,setToast]=useState('');const [member,setMember]=useState<Person|null>(null);const [emojiOpen,setEmojiOpen]=useState(false);const [pendingFile,setPendingFile]=useState<Message['attachment']>();const [voiceChannel,setVoiceChannel]=useState('The Lounge');const fileRef=useRef<HTMLInputElement>(null);const searchRef=useRef<HTMLInputElement>(null);const scrollRef=useRef<HTMLDivElement>(null);
 const guild=s.guilds.find(g=>g.id===s.selectedGuild);const channel=s.channels.find(c=>c.id===s.selectedChannel);const currentMessages=s.messages.filter(m=>m.channel===s.selectedChannel&&(!showPins||m.pinned));
 const virtual=useVirtualizer({count:currentMessages.length,getScrollElement:()=>scrollRef.current,estimateSize:i=>currentMessages[i]?.image?300:100,overscan:6});
 const notify=(text:string)=>setToast(text);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearchOpen(true);searchRef.current?.focus();}if(e.key==='Escape'){setSearchOpen(false);setEmojiOpen(false);setMobileNav(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{setDraft('');setReply(null);setEditing(null);setPendingFile(undefined);setShowPins(false);},[s.selectedChannel]);
 const selectChannel=(id:string)=>{s.select(s.selectedGuild,id);setView('chat');setMobileNav(false);};
 function send(e:FormEvent){e.preventDefault();if(!draft.trim()&&!pendingFile)return;if(editing){s.edit(editing.id,draft.trim());setEditing(null);}else{s.send(draft.trim(),reply?.id,pendingFile);}setDraft('');setReply(null);setPendingFile(undefined);setEmojiOpen(false);requestAnimationFrame(()=>virtual.scrollToIndex(currentMessages.length,{align:'end'}));}
 const foundMessages=s.messages.filter(m=>m.content.toLowerCase().includes(query.toLowerCase()));
 if(connected)return <Suspense fallback={<div className="empty-state">Opening your workspace…</div>}><ConnectedWorkspace onExit={()=>setConnected(false)}/></Suspense>;
 return <div className="app-shell">
  <header className="topbar"><div className="wordmark"><Mark small/><span>vexa</span><span className="beta-tag">BETA</span></div><div className="topbar-center"><span className="top-divider"/><span>Your squad, in sync.</span></div><div className="global-search"><Search size={16}/><input ref={searchRef} value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);}} placeholder="Search Vexa" aria-label="Search Vexa"/><kbd>Ctrl K</kbd></div><div className="top-actions"><span className="demo-label">LOCAL DEMO</span><IconButton label="Inbox" onClick={()=>setModal('inbox')}><Inbox size={19}/></IconButton><button className="profile-top" onClick={()=>setModal('profile')} aria-label="Your profile"><Avatar person={s.profile} size={29}/></button></div></header>
  <div className="workspace">
   <nav className="server-rail" aria-label="Servers"><button className={`server-button home ${s.selectedGuild==='home'?'selected':''}`} title="Friends and direct messages" aria-label="Friends and direct messages" onClick={()=>{s.select('home');setView('friends');}}><Mark/></button><div className="rail-divider"/>{s.guilds.map(g=><button key={g.id} title={g.name} aria-label={g.name} onClick={()=>{s.select(g.id);setView('chat');}} className={`server-button ${s.selectedGuild===g.id?'selected':''}`} style={{'--server-color':g.color} as React.CSSProperties}>{g.id==='nexus'?<Gamepad2 size={27}/>:g.id==='valorant'?<Zap size={25}/>:g.id==='forge'?<Shield size={25}/>:g.initials}{g.id==='valorant'&&<span className="server-badge">3</span>}</button>)}<button className="server-button add-server" title="Create a server" aria-label="Create a server" onClick={()=>setModal('server')}><Plus size={25}/></button><div className="rail-bottom"><IconButton label="Explore communities" onClick={()=>setModal('explore')}><Compass size={25}/></IconButton><button className="rail-avatar" onClick={()=>setModal('profile')} aria-label="Edit profile"><Avatar person={s.profile} size={38}/></button></div></nav>
   {mobileNav&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}
   <aside className={`channel-sidebar ${mobileNav?'mobile-open':''}`}>
    <button className="server-heading" onClick={()=>setModal(s.selectedGuild==='home'?'profile':'server-menu')}><span>{s.selectedGuild==='home'?'Your space':guild?.name}</span><ChevronDown size={18}/></button>
    {s.selectedGuild!=='home'?<><div className="server-banner"><img src={`${import.meta.env.BASE_URL}nebula.png`} alt="Violet eclipse over an alien landscape"/><div className="banner-shade"/><span className="server-level"><Sparkles size={12}/> YOUR NEXT ADVENTURE</span><strong>Find your people.</strong></div><button className="invite-button" onClick={()=>setModal('invite')}><Users size={15}/> Invite your friends <Plus size={15}/></button><div className="channels-scroll">{['START HERE','THE COMMUNITY','VOICE CHANNELS'].map(category=><section className="channel-category" key={category}><div className="category-heading"><span><ChevronDown size={12}/>{category}</span><IconButton label={`Add ${category==='VOICE CHANNELS'?'voice':'text'} channel`} onClick={()=>setModal(category==='VOICE CHANNELS'?'voice-channel':'channel')}><Plus size={14}/></IconButton></div>{s.channels.filter(c=>c.guild===s.selectedGuild&&c.category===category).map(c=><div key={c.id}><button className={`channel ${c.id===s.selectedChannel&&view==='chat'?'selected':''}`} onClick={()=>{if(c.kind==='voice'){setVoiceChannel(c.name);setView('voice');setMobileNav(false);}else selectChannel(c.id);}}>{c.kind==='voice'?<Volume2 size={18}/>:c.id==='announcements'?<Radio size={18}/>:<Hash size={18}/>}<span>{c.name}</span>{c.id==='lfg'&&!s.read.includes(c.id)&&<b className="channel-count">2</b>}{c.kind==='voice'&&c.id==='lounge'&&<span className="voice-count">3</span>}</button>{c.id==='lounge'&&<div className="voice-mini">{people.slice(1,4).map(p=><button title={p.name} key={p.id} onClick={()=>setMember(p)}><Avatar person={p} size={25} status={false}/></button>)}<span>hanging out</span></div>}</div>)}</section>)}<button className={`voice-history-link ${view==='voice'?'selected':''}`} onClick={()=>{setView('voice');setMobileNav(false);}}><span className="transcript-icon"><FileText size={17}/></span><span>Voice history<small>Never miss a moment</small></span><span className="new-label">NEW</span></button></div></>:<div className="channels-scroll"><button className={`channel ${view==='friends'?'selected':''}`} onClick={()=>setView('friends')}><Users size={18}/>Friends<span className="channel-count">{s.friends.length}</span></button><div className="category-heading"><span>DIRECT MESSAGES</span><IconButton label="New direct message" onClick={()=>setModal('dm')}><Plus size={15}/></IconButton></div>{s.channels.filter(c=>c.kind==='dm').map(c=><button className={`channel dm-channel ${c.id===s.selectedChannel&&view==='chat'?'selected':''}`} key={c.id} onClick={()=>selectChannel(c.id)}><Avatar person={people.find(p=>`dm-${p.id}`===c.id)??people[1]} size={28}/>{c.name}</button>)}</div>}
    <div className="connection-note"><span className="status-dot"/>Local workspace <button onClick={()=>setModal('connect')}>{CONNECT_AVAILABLE?'Connect account':'About connected mode'} <ArrowUpRight size={12}/></button></div>
    <div className="user-panel"><button className="user-info" onClick={()=>setModal('profile')}><Avatar person={s.profile} size={34}/><span><strong>{s.profile.name}</strong><small>{s.profile.status==='dnd'?'Do not disturb':s.profile.status[0].toUpperCase()+s.profile.status.slice(1)}</small></span></button><IconButton label={muted?'Unmute microphone':'Mute microphone'} active={muted} onClick={()=>setMuted(!muted)}>{muted?<MicOff size={17}/>:<Mic size={17}/>}</IconButton><IconButton label={deafened?'Undeafen':'Deafen'} active={deafened} onClick={()=>setDeafened(!deafened)}>{deafened?<HeadphoneOff size={17}/>:<Headphones size={17}/>}</IconButton><IconButton label="User settings" onClick={()=>setModal('profile')}><Settings size={17}/></IconButton></div>
   </aside>
   <main className="main-area">
    <div className="channel-header"><IconButton label="Toggle channels" className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></IconButton><span className="channel-header-icon">{view==='friends'?<Users size={23}/>:view==='voice'?<FileText size={23}/>:channel?.kind==='dm'?<MessageCircle size={23}/>:<Hash size={25}/>}</span><h1>{view==='friends'?'Friends':view==='voice'?'voice-history':channel?.name??'general'}</h1><span className="header-separator"/><p>{view==='voice'?'The conversation continues.':view==='friends'?'Better together.':channel?.description??'A space for your squad.'}</p><div className="channel-actions"><IconButton label={notifications?'Mute notifications':'Enable notifications'} active={!notifications} onClick={()=>{setNotifications(!notifications);notify(notifications?'Channel notifications muted':'Channel notifications enabled');}}>{notifications?<Bell size={18}/>:<BellOff size={18}/>}</IconButton><IconButton label="Pinned messages" active={showPins} onClick={()=>{setView('chat');setShowPins(!showPins);}}><Pin size={18}/></IconButton><IconButton label="Toggle member list" active={showMembers} onClick={()=>setShowMembers(!showMembers)}><Users size={20}/></IconButton><span className="header-separator"/><IconButton label="Channel details" onClick={()=>setModal('channel-info')}><MoreHorizontal size={22}/></IconButton></div></div>
    <div className="content-layout"><div className="conversation">
    {view==='friends'?<div className="friends-view"><div className="section-title"><div><span className="eyebrow">YOUR PEOPLE</span><h2>Good company.<br/><span>Great games.</span></h2></div><button className="primary-button" onClick={()=>setModal('dm')}><Plus size={16}/> Add a friend</button></div><div className="friends-heading">ALL FRIENDS — {s.friends.length}</div>{people.filter(p=>s.friends.includes(p.id)).map(p=><div className="friend-row" key={p.id}><Avatar person={p}/><div><strong>{p.name}</strong><small>{p.activity??p.status}</small></div><IconButton label={`Message ${p.name}`} onClick={()=>{s.openDM(p.id);setView('chat');}}><MessageCircle size={20}/></IconButton><IconButton label={`View ${p.name}'s profile`} onClick={()=>setMember(p)}><MoreHorizontal size={20}/></IconButton></div>)}</div>
    :view==='voice'?<div className="voice-view"><Recall demo channel={voiceChannel}/></div>
    :<><div className="chat-scroll" ref={scrollRef}><div className="welcome-block"><span className="welcome-hash">{channel?.kind==='dm'?<MessageCircle size={33}/>:<Hash size={36}/>}</span><div><span className="eyebrow">{channel?.kind==='dm'?'YOUR CONVERSATION STARTS HERE':'YOU’RE IN GOOD COMPANY'}</span><h2>{channel?.kind==='dm'?`Say hey to ${channel.name}`:`Welcome to #${channel?.name??'general'}`}</h2><p>{channel?.kind==='dm'?'A little less noise. A little more connection.':'This is where the squad comes together. Make yourself at home.'}</p></div></div><div className="date-divider"><span/>{showPins?'PINNED MESSAGES':'SEPTEMBER 24, 2026'}<span/></div>{showPins&&currentMessages.length===0&&<div className="empty-state"><Pin size={26}/><h3>No pins yet</h3><p>Pin a message to keep it close.</p></div>}{!showPins&&currentMessages.length===0&&<div className="empty-state"><MessageCircle size={27}/><h3>A fresh start</h3><p>Be the first to say something.</p></div>}<div className="virtual-messages" style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(row=>{const m=currentMessages[row.index];return <div key={m.id} ref={virtual.measureElement} data-index={row.index} style={{position:'absolute',top:0,left:0,width:'100%',transform:`translateY(${row.start}px)`}}><MessageRow message={m} onReply={()=>{setReply(m);document.getElementById('message-input')?.focus();}} onEdit={()=>{setEditing(m);setDraft(m.content);document.getElementById('message-input')?.focus();}} onMember={()=>setMember(m.author==='you'?s.profile:people.find(p=>p.id===m.author)??people[1])} onImage={()=>setModal('image')}/></div>;})}</div></div>
    <div className="composer-area">{reply&&<div className="reply-bar"><Reply size={14}/> Replying to <strong>{people.find(p=>p.id===reply.author)?.name}</strong><span>{reply.content.slice(0,70)}</span><IconButton label="Cancel reply" onClick={()=>setReply(null)}><X size={15}/></IconButton></div>}{editing&&<div className="reply-bar"><Pencil size={14}/> Editing your message<IconButton label="Cancel edit" onClick={()=>{setEditing(null);setDraft('');}}><X size={15}/></IconButton></div>}{pendingFile&&<div className="reply-bar"><FileText size={15}/>{pendingFile.name}<IconButton label="Remove attachment" onClick={()=>setPendingFile(undefined)}><X size={15}/></IconButton></div>}<form className="composer" onSubmit={send}><IconButton label="Attach a file" onClick={()=>fileRef.current?.click()}><Plus size={22}/></IconButton><input ref={fileRef} type="file" hidden accept="image/png,image/jpeg,image/webp,text/plain,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){notify('Local demo attachments are limited to 1 MB.');return;}if(!['image/png','image/jpeg','image/webp','text/plain','application/pdf'].includes(f.type)){notify('Choose a PNG, JPEG, WebP, text file, or PDF.');return;}const reader=new FileReader();reader.onload=()=>setPendingFile({name:f.name,data:String(reader.result)});reader.readAsDataURL(f);e.target.value='';}}/><textarea id="message-input" rows={1} maxLength={4000} aria-label="Message" placeholder={`Message ${channel?.kind==='dm'?'@':'#'}${channel?.name??'general'}`} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(e);}}}/><IconButton label="Add emoji" active={emojiOpen} onClick={()=>setEmojiOpen(!emojiOpen)}><Smile size={21}/></IconButton><span className="composer-divider"/><button type="submit" className="send-button" aria-label={editing?'Save edit':'Send message'} disabled={!draft.trim()&&!pendingFile}>{editing?<Check size={18}/>:<Send size={18}/>}</button>{emojiOpen&&<div className="emoji-picker">{['💜','🔥','🎮','👀','✨','😂','🙌','GG','🚀','❤️','👍','⚡'].map(e=><button type="button" key={e} onClick={()=>{setDraft(d=>d+e);setEmojiOpen(false);}}>{e}</button>)}</div>}</form><div className="composer-footer"><span><span className="status-dot"/> You’re all caught up</span><span><kbd>Enter</kbd> to send <i>·</i> <kbd>Shift + Enter</kbd> for a new line</span></div></div></>}
    </div>
    {showMembers&&<aside className="members-sidebar"><div className="members-heading"><span>MEMBERS</span><span>{people.length}</span></div><div className="member-group-label">ONLINE — {people.filter(p=>p.status!=='offline').length}</div>{people.filter(p=>p.status!=='offline').map(p=><button className="member" key={p.id} onClick={()=>setMember(p.id==='you'?s.profile:p)}><Avatar person={p.id==='you'?s.profile:p} size={34}/><span><strong style={{color:p.role==='Admin'?'#b9a0ff':undefined}}>{p.id==='you'?s.profile.name:p.name}{p.role==='Admin'&&<Crown size={12}/>}</strong><small>{p.activity??'Online'}</small></span></button>)}<div className="member-group-label offline-label">OFFLINE — 2</div>{people.filter(p=>p.status==='offline').map(p=><button className="member offline-member" key={p.id} onClick={()=>setMember(p)}><Avatar person={p} size={34}/><span><strong>{p.name}</strong><small>Offline</small></span></button>)}<div className="squad-card"><div className="squad-card-icon"><Headphones size={22}/><span className="status-dot"/></div><h3>Better with voice.</h3><p>Drop in. Hang out.<br/>Make it a good game.</p><button onClick={()=>{setVoiceChannel('The Lounge');setModal('voice-info');}}>Join The Lounge <ArrowUpRight size={15}/></button></div><span className="sidebar-bottom">A LITTLE LESS NOISE.<br/>A LOT MORE CONNECTION.</span></aside>}
    </div>
   </main>
  </div>
  {searchOpen&&<><button className="search-dismiss" aria-label="Close search" onClick={()=>setSearchOpen(false)}/><div className="search-results"><div className="search-heading">{query?`RESULTS FOR “${query}”`:'JUMP TO A CHANNEL'}<IconButton label="Close search" onClick={()=>setSearchOpen(false)}><X size={15}/></IconButton></div>{!query?s.channels.filter(c=>c.kind!=='voice').slice(0,8).map(c=><button key={c.id} onClick={()=>{s.select(c.guild,c.id);setView('chat');setSearchOpen(false);}}><Hash size={17}/><span>{c.name}<small>{s.guilds.find(g=>g.id===c.guild)?.name??'Direct message'}</small></span><ArrowUpRight size={16}/></button>):foundMessages.length?foundMessages.slice(0,12).map(m=><button key={m.id} onClick={()=>{const c=s.channels.find(c=>c.id===m.channel);if(c){s.select(c.guild,c.id);setView('chat');setShowPins(false);setSearchOpen(false);setTimeout(()=>{const index=s.messages.filter(x=>x.channel===c.id).findIndex(x=>x.id===m.id);virtual.scrollToIndex(index,{align:'center'});},150);}}}><MessageCircle size={17}/><span>{m.content.slice(0,110)}<small>#{s.channels.find(c=>c.id===m.channel)?.name??'Direct message'} · {m.time}</small></span></button>):<p className="empty-state">No messages found.</p>}</div></>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {member&&<Modal title="Member profile" description="Get to know your squad." onClose={()=>setMember(null)}><div className="profile-card"><Avatar person={member} size={78}/><h2>{member.name}</h2><span className="role-pill"><Shield size={13}/>{member.role}</span><p>{member.activity??'Taking a break'}</p>{member.id!=='you'&&<div className="button-row"><button className="primary-button" onClick={()=>{s.openDM(member.id);setView('chat');setMember(null);}}><MessageCircle size={17}/>Message</button><button className="secondary-button" onClick={()=>s.addFriend(member.id)}>{s.friends.includes(member.id)?'Remove friend':'Add friend'}</button></div>}</div></Modal>}
  {modal&&<Modal title={modalTitles[modal]??'Vexa'} description={modalDescriptions[modal]} onClose={()=>setModal(null)}>
   {(modal==='server'||modal==='channel'||modal==='voice-channel')&&<CreateForm type={modal} onDone={()=>{setModal(null);setView('chat');notify('Your space is ready.');}}/>}
   {modal==='profile'&&<ProfileForm close={()=>{setModal(null);notify('Profile updated');}}/>}
   {modal==='dm'&&<div className="people-picker">{people.filter(p=>p.id!=='you').map(p=><div className="friend-row" key={p.id}><Avatar person={p}/><div><strong>{p.name}</strong><small>{p.status}</small></div><IconButton label={`Add ${p.name} as a friend`} onClick={()=>{s.addFriend(p.id);notify(s.friends.includes(p.id)?'Friend removed':'Friend added');}}>{s.friends.includes(p.id)?<Check size={19}/>:<Plus size={19}/>}</IconButton><IconButton label={`Message ${p.name}`} onClick={()=>{s.openDM(p.id);setView('chat');setModal(null);}}><MessageCircle size={20}/></IconButton></div>)}</div>}
   {modal==='invite'&&<><div className="notice"><Users size={22}/><p>Server invites need a connected backend. In this local demo, share a preview of Vexa with your friends.</p></div><label className="field-label">PREVIEW LINK</label><div className="copy-field"><input readOnly value={window.location.origin}/><button className="primary-button" onClick={()=>{navigator.clipboard.writeText(window.location.origin).then(()=>notify('Preview link copied')).catch(()=>notify('Select and copy the link manually.'));}}><Copy size={16}/>Copy</button></div></>}
   {modal==='server-menu'&&<div className="menu-list"><button onClick={()=>setModal('invite')}><Users size={19}/>Invite people<ChevronRight size={17}/></button><button onClick={()=>setModal('channel')}><Hash size={19}/>Create channel<ChevronRight size={17}/></button><button onClick={()=>setModal('roles')}><Shield size={19}/>Roles & permissions<ChevronRight size={17}/></button><button onClick={()=>setModal('server')}><Plus size={19}/>Create a server<ChevronRight size={17}/></button></div>}
   {modal==='roles'&&<><div className="role-list">{['Admin','Moderator','Member'].map((role,i)=><div key={role}><Shield size={18}/><strong>{role}</strong><span>{['Full server access','Manage conversations','Chat and connect'][i]}</span></div>)}</div><p className="muted-text">Demo roles are illustrative. The API uses shared permission bitfields and channel overrides; role-management controls are a later integration step.</p></>}
   {modal==='inbox'&&<div className="empty-state"><Inbox size={35}/><h3>All quiet on your radar.</h3><p>You have no new mentions in this local workspace.</p></div>}
   {modal==='explore'&&<div className="explore-list">{s.guilds.map(g=><button key={g.id} onClick={()=>{s.select(g.id);setView('chat');setModal(null);}}><span style={{color:g.color}}><Gamepad2 size={25}/></span><strong>{g.name}<small>Your communities</small></strong><ArrowUpRight size={19}/></button>)}</div>}
   {modal==='channel-info'&&<div className="channel-details"><span className="welcome-hash"><Hash size={32}/></span><h2>{channel?.name??'Your space'}</h2><p>{channel?.description??'Bring your ideas, your clips, and your best company.'}</p><span className="role-pill">{currentMessages.length} messages in this workspace</span></div>}
   {modal==='voice-info'&&<><div className="notice"><Headphones size={30}/><div><h3>Voice is on the roadmap.</h3><p>The mediasoup call service isn’t connected in this pass. Joining here would not connect you to another person.</p></div></div><button className="primary-button full-width" onClick={()=>{setView('voice');setModal(null);}}>Explore voice history <ArrowUpRight size={16}/></button></>}
   {modal==='connect'&&<ConnectForm onDone={()=>{setModal(null);setConnected(true);}} available={CONNECT_AVAILABLE}/>}
   {modal==='image'&&<img className="image-preview" src={`${import.meta.env.BASE_URL}nebula.png`} alt="Ultraviolet alien landscape beneath a luminous eclipse"/>}
  </Modal>}
 </div>;
}

function MessageRow({message:m,onReply,onEdit,onMember,onImage}:{message:Message;onReply:()=>void;onEdit:()=>void;onMember:()=>void;onImage:()=>void}) {
 const s=useStore();const p=m.author==='you'?s.profile:people.find(p=>p.id===m.author)??people[1];const referenced=s.messages.find(x=>x.id===m.reply);const [confirmDelete,setConfirmDelete]=useState(false);
 return <article className="message-row"><button className="message-avatar" onClick={onMember} aria-label={`View ${p.name}'s profile`}><Avatar person={p} status={false}/></button><div className="message-body">{referenced&&<div className="reply-preview"><Reply size={13}/><strong>{people.find(p=>p.id===referenced.author)?.name}</strong><span>{referenced.content.slice(0,90)}</span></div>}<div className="message-meta"><button onClick={onMember} style={{color:p.color}}>{p.name}</button>{p.role==='Admin'&&<span className="message-role">{p.id==='you'?'YOU':'ADMIN'}</span>}<time>{m.time}</time>{m.edited&&<small>(edited)</small>}{m.pinned&&<Pin size={12}/>}</div><div className="message-content"><Markdown remarkPlugins={[remarkGfm]} components={{a:({children,href})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>,img:()=>null}}>{m.content}</Markdown></div>{m.image&&<button className="message-image" onClick={onImage}><img src={m.image} alt="Alien mountains under a purple eclipse"/><span><Sparkles size={13}/> A world worth getting lost in. <ArrowUpRight size={15}/></span></button>}{m.attachment&&<a className="attachment" href={m.attachment.data} download={m.attachment.name}><FileText size={22}/><span>{m.attachment.name}<small>Local attachment</small></span><ArrowDown size={17}/></a>}<MessageReactions reactions={Object.entries(m.reactions).map(([emoji,users])=>({emoji,count:users.length,reacted:users.includes('you')}))} onToggle={emoji=>s.react(m.id,emoji)}/></div><div className="message-toolbar"><IconButton label="React with fire" onClick={()=>s.react(m.id,'🔥')}><Smile size={16}/></IconButton><IconButton label="Reply to message" onClick={onReply}><Reply size={16}/></IconButton><IconButton label={m.pinned?'Unpin message':'Pin message'} active={m.pinned} onClick={()=>s.pin(m.id)}><Pin size={15}/></IconButton>{m.author==='you'&&<><IconButton label="Edit message" onClick={onEdit}><Pencil size={15}/></IconButton><IconButton label="Delete message" onClick={()=>setConfirmDelete(true)}><Trash2 size={15}/></IconButton></>}</div>{confirmDelete&&<Modal title="Delete this message?" description="This removes the message from this local workspace." onClose={()=>setConfirmDelete(false)}><p>{m.content}</p><div className="button-row"><button className="secondary-button" onClick={()=>setConfirmDelete(false)}>Keep message</button><button className="danger-button" onClick={()=>{s.remove(m.id);setConfirmDelete(false);}}>Delete message</button></div></Modal>}</article>;
}
const modalTitles:Record<string,string>={server:'Create your server',channel:'Create a text channel','voice-channel':'Create a voice channel',profile:'Your profile',dm:'Find your people',invite:'Bring your squad',roles:'Roles & permissions',inbox:'Your inbox',explore:'Your communities','server-menu':'Server settings','channel-info':'About this channel','voice-info':'Meet in The Lounge',connect:'Connect to Vexa',image:'Beyond the familiar'};
const modalDescriptions:Record<string,string>={server:'Every great squad needs a place to call home.',channel:'Give the conversation a place to happen.','voice-channel':'Make room for a little more connection.',profile:'Let the community know who you are.',dm:'Start a conversation or add someone to your friends.',connect:'Local demo data stays on this device. Connect to your running API to use a real account.',image:'Original Vexa artwork.'};
function CreateForm({type,onDone}:{type:string;onDone:()=>void}) {const [name,setName]=useState('');const s=useStore();return <form onSubmit={e=>{e.preventDefault();if(!name.trim())return;if(type==='server')s.addGuild(name.trim());else s.addChannel(name.trim(),type==='voice-channel'?'voice':'text');onDone();}}><label className="field-label" htmlFor="new-name">{type==='server'?'SERVER NAME':'CHANNEL NAME'}</label><input autoFocus className="form-input" id="new-name" placeholder={type==='server'?'The midnight squad':'squad-chat'} value={name} maxLength={60} onChange={e=>setName(e.target.value)} required/><p className="muted-text">Created in your local demo workspace.</p><button className="primary-button full-width" disabled={!name.trim()} type="submit">Create {type==='server'?'server':'channel'}<ArrowUpRight size={17}/></button></form>;}
function ProfileForm({close}:{close:()=>void}) {const s=useStore();const [name,setName]=useState(s.profile.name);const [status,setStatus]=useState(s.profile.status);const [activity,setActivity]=useState(s.profile.activity??'');const [avatar,setAvatar]=useState(s.profile.avatar??defaultAvatar(s.profile.id));return <form onSubmit={e=>{e.preventDefault();s.updateProfile({name:name.trim(),initials:name.trim().slice(0,1).toUpperCase(),status,activity,avatar});close();}}><div className="profile-editor-avatar"><Avatar person={{...s.profile,name,avatar,initials:name.slice(0,1).toUpperCase(),status}} size={72}/><span>Your next adventure starts with you.</span></div><AvatarPicker id={s.profile.id} value={avatar} onChange={setAvatar}/><label className="field-label" htmlFor="profile-name">DISPLAY NAME</label><input className="form-input" id="profile-name" value={name} maxLength={30} required onChange={e=>setName(e.target.value)}/><label className="field-label" htmlFor="profile-status">STATUS</label><select className="form-input" id="profile-status" value={status} onChange={e=>setStatus(e.target.value as Person['status'])}><option value="online">Online</option><option value="idle">Idle</option><option value="dnd">Do not disturb</option><option value="offline">Invisible</option></select><label className="field-label" htmlFor="activity">WHAT’S YOUR VIBE?</label><input className="form-input" id="activity" value={activity} maxLength={80} onChange={e=>setActivity(e.target.value)}/><button className="primary-button full-width" disabled={!name.trim()} type="submit">Save profile<Check size={16}/></button></form>;}
function ConnectForm({onDone,available}:{onDone:()=>void;available:boolean}) {
 if(!available)return <div className="notice"><Radio size={26}/><div><h3>No live backend on this deployment.</h3><p>This is a static preview (GitHub Pages or Vercel) with no API, gateway, Postgres or Redis behind it, so there’s no real server to sign in to here. Clone the repo and run <code>pnpm dev</code> with the local stack (see <code>docs/BACKEND.md</code>) to use real accounts.</p></div></div>;
 return <div className="notice"><Radio size={26}/><div><h3>Your real community starts here.</h3><p>Sign in or create an account on your running Vexa server. Your demo conversations stay separate from your connected workspace.</p><button className="primary-button" style={{marginTop:18}} onClick={onDone}>Open connected workspace <ArrowUpRight size={16}/></button></div></div>;
}
