import Fastify from 'fastify';import cookie from '@fastify/cookie';import cors from '@fastify/cors';import rateLimit from '@fastify/rate-limit';import argon2 from 'argon2';import {randomBytes,createHash} from 'node:crypto';import {z,ZodError} from 'zod';
import {Snowflake,registerSchema,credentialsSchema,guildSchema,channelSchema,messageSchema,editMessageSchema,snowflakeSchema,DEFAULT_PERMISSIONS,Permission,hasPermission} from '@vexa/shared';import {db,redis,requireChannel,publish} from './db.js';
declare module 'fastify' {interface FastifyRequest {userId:string}}
const app=Fastify({logger:true,bodyLimit:32768});const ids=new Snowflake(Number(process.env.WORKER_ID??1));const origin=process.env.WEB_ORIGIN??'http://localhost:5173';
await app.register(cookie);await app.register(cors,{origin,credentials:true});await app.register(rateLimit,{redis,max:120,timeWindow:'1 minute'});
app.decorateRequest('userId','');
const hash=(token:string)=>createHash('sha256').update(token).digest('hex');
app.addHook('onRequest',async(req,reply)=>{
 if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin!==origin)return reply.code(403).send({error:'Invalid request origin'});
 if(req.url==='/health'||req.url.startsWith('/auth/')||req.method==='OPTIONS')return;
 const token=req.cookies.vexa_session;if(!token)return reply.code(401).send({error:'Sign in required'});
 const {rows:[session]}=await db.query('SELECT user_id FROM sessions WHERE token_hash=$1 AND expires_at>now()',[hash(token)]);if(!session)return reply.code(401).send({error:'Session expired'});req.userId=session.user_id;
});
app.setErrorHandler((error,req,reply)=>{if(error instanceof ZodError)return reply.code(400).send({error:'Invalid request',issues:error.issues});const e=error as Error&{code?:string;statusCode?:number};if(e.code==='23505')return reply.code(409).send({error:'Already exists'});if(e.code==='23503')return reply.code(400).send({error:'Referenced resource does not exist'});if(e.statusCode&&e.statusCode<500)return reply.code(e.statusCode).send({error:e.message});req.log.error(error);return reply.code(503).send({error:'Service temporarily unavailable'});});
async function createSession(userId:string,reply:import('fastify').FastifyReply){const token=randomBytes(32).toString('hex');await db.query("INSERT INTO sessions VALUES($1,$2,now()+interval '30 days')",[hash(token),userId]);reply.setCookie('vexa_session',token,{path:'/',httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:2592000});}
const params=(value:unknown,key:string)=>snowflakeSchema.parse((value as Record<string,unknown>)[key]);
app.get('/health',async()=>{await db.query('SELECT 1');await redis.ping();return {ok:true};});
app.post('/auth/register',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{const body=registerSchema.parse(req.body);const id=ids.next();await db.query('INSERT INTO users(id,email,username,password_hash) VALUES($1,$2,$3,$4)',[id,body.email,body.username,await argon2.hash(body.password,{type:argon2.argon2id})]);await createSession(id,reply);return reply.code(201).send({id,username:body.username,email:body.email});});
app.post('/auth/login',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req,reply)=>{const body=credentialsSchema.parse(req.body);const {rows:[user]}=await db.query('SELECT * FROM users WHERE email=$1',[body.email]);if(!user||!await argon2.verify(user.password_hash,body.password))return reply.code(401).send({error:'Invalid credentials'});await createSession(user.id,reply);return {id:user.id,username:user.username,email:user.email};});
app.post('/auth/logout',async(req,reply)=>{if(req.cookies.vexa_session)await db.query('DELETE FROM sessions WHERE token_hash=$1',[hash(req.cookies.vexa_session)]);reply.clearCookie('vexa_session',{path:'/'});return {ok:true};});
app.get('/me',async(req)=>{const {rows:[user]}=await db.query('SELECT id,username,email,avatar_url,bio FROM users WHERE id=$1',[req.userId]);return user;});
app.get('/guilds',async(req)=>(await db.query('SELECT g.* FROM guilds g JOIN guild_members m ON m.guild_id=g.id WHERE m.user_id=$1 ORDER BY g.id',[req.userId])).rows);
const inviteCodeSchema=z.string().regex(/^[A-Za-z0-9_-]{24}$/);
app.post('/guilds/:guildId/invites',{config:{rateLimit:{max:15,timeWindow:'1 minute'}}},async(req,reply)=>{
 const guildId=params(req.params,'guildId');const {rowCount}=await db.query('SELECT 1 FROM guilds WHERE id=$1 AND owner_id=$2',[guildId,req.userId]);
 if(!rowCount)return reply.code(403).send({error:'Only the server owner can create invites'});
 const code=randomBytes(18).toString('base64url');const {rows:[invite]}=await db.query("INSERT INTO invites(code,guild_id,created_by,expires_at,max_uses) VALUES($1,$2,$3,now()+interval '7 days',100) RETURNING code,expires_at,max_uses",[code,guildId,req.userId]);
 return reply.code(201).send(invite);
});
app.get('/invites/:code',async(req,reply)=>{const code=inviteCodeSchema.parse((req.params as {code:string}).code);const {rows:[invite]}=await db.query('SELECT g.id,g.name,i.expires_at,i.max_uses,i.uses FROM invites i JOIN guilds g ON g.id=i.guild_id WHERE i.code=$1 AND i.expires_at>now()',[code]);if(!invite)return reply.code(404).send({error:'Invite is invalid or expired'});return invite;});
app.post('/invites/:code/join',{config:{rateLimit:{max:15,timeWindow:'1 minute'}}},async(req,reply)=>{
 const code=inviteCodeSchema.parse((req.params as {code:string}).code),client=await db.connect();
 try {await client.query('BEGIN');const {rows:[invite]}=await client.query('SELECT * FROM invites WHERE code=$1 FOR UPDATE',[code]);
  if(!invite||!invite.expires_at||new Date(invite.expires_at)<=new Date())throw Object.assign(new Error('Invite is invalid or expired'),{statusCode:404});
  if((await client.query('SELECT 1 FROM bans WHERE guild_id=$1 AND user_id=$2',[invite.guild_id,req.userId])).rowCount)throw Object.assign(new Error('You cannot join this server'),{statusCode:403});
  const alreadyJoined=(await client.query('SELECT 1 FROM guild_members WHERE guild_id=$1 AND user_id=$2',[invite.guild_id,req.userId])).rowCount;
  if(!alreadyJoined){if(invite.max_uses!==null&&invite.uses>=invite.max_uses)throw Object.assign(new Error('Invite has reached its use limit'),{statusCode:409});const joined=await client.query('INSERT INTO guild_members(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[invite.guild_id,req.userId]);if(joined.rowCount)await client.query('UPDATE invites SET uses=uses+1 WHERE code=$1',[code]);}
  const {rows:[guild]}=await client.query('SELECT id,name,owner_id FROM guilds WHERE id=$1',[invite.guild_id]);await client.query('COMMIT');return reply.code(alreadyJoined?200:201).send(guild);
 }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
});
app.post('/guilds',async(req,reply)=>{const body=guildSchema.parse(req.body),id=ids.next(),channelId=ids.next();const client=await db.connect();try{await client.query('BEGIN');await client.query('INSERT INTO guilds(id,name,owner_id) VALUES($1,$2,$3)',[id,body.name,req.userId]);await client.query('INSERT INTO guild_members(guild_id,user_id) VALUES($1,$2)',[id,req.userId]);await client.query("INSERT INTO roles(id,guild_id,name,permissions) VALUES($1,$1,'@everyone',$2)",[id,DEFAULT_PERMISSIONS.toString()]);await client.query("INSERT INTO channels(id,guild_id,name,type) VALUES($1,$2,'general','text')",[channelId,id]);await client.query('COMMIT');return reply.code(201).send({id,name:body.name,owner_id:req.userId,channelId});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
app.get('/guilds/:guildId/channels',async(req)=>{const guildId=params(req.params,'guildId');const {rows}=await db.query('SELECT c.* FROM channels c JOIN guild_members m ON m.guild_id=c.guild_id WHERE c.guild_id=$1 AND m.user_id=$2 ORDER BY c.position,c.id',[guildId,req.userId]);const visible=[];for(const c of rows){try{await requireChannel(req.userId,c.id);visible.push(c);}catch(error){if((error as {statusCode?:number}).statusCode!==403)throw error;}}return visible;});
app.get('/guilds/:guildId/members',async(req,reply)=>{const id=params(req.params,'guildId');const {rowCount}=await db.query('SELECT 1 FROM guild_members WHERE guild_id=$1 AND user_id=$2',[id,req.userId]);if(!rowCount)return reply.code(403).send({error:'Guild access denied'});return (await db.query('SELECT u.id,u.username,u.avatar_url,m.nickname FROM guild_members m JOIN users u ON u.id=m.user_id WHERE m.guild_id=$1 ORDER BY u.username LIMIT 100',[id])).rows;});
app.post('/guilds/:guildId/channels',async(req,reply)=>{const guildId=params(req.params,'guildId'),body=channelSchema.parse(req.body);const {rows:[guild]}=await db.query('SELECT * FROM guilds WHERE id=$1 AND owner_id=$2',[guildId,req.userId]);if(!guild)return reply.code(403).send({error:'Only the guild owner can create channels in this release'});if(body.parentId){const {rows:[parent]}=await db.query("SELECT id FROM channels WHERE id=$1 AND guild_id=$2 AND type='category'",[body.parentId,guildId]);if(!parent)return reply.code(400).send({error:'Invalid category'});}const id=ids.next();const {rows:[channel]}=await db.query('INSERT INTO channels(id,guild_id,name,type,parent_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[id,guildId,body.name,body.type,body.parentId??null]);return reply.code(201).send(channel);});
app.get('/channels/:channelId/messages',async(req)=>{const id=params(req.params,'channelId');await requireChannel(req.userId,id);const query=z.object({before:snowflakeSchema.optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).parse(req.query);return (await db.query('SELECT m.*,u.username FROM messages m JOIN users u ON u.id=m.author_id WHERE m.channel_id=$1 AND ($2::bigint IS NULL OR m.id<$2) ORDER BY m.id DESC LIMIT $3',[id,query.before??null,query.limit])).rows;});
app.post('/channels/:channelId/messages',async(req,reply)=>{const id=params(req.params,'channelId'),body=messageSchema.parse(req.body);const {channel}=await requireChannel(req.userId,id,Permission.SEND_MESSAGES);if(channel.type!=='text')return reply.code(400).send({error:'Messages require a text channel'});if(body.replyTo){const {rowCount}=await db.query('SELECT 1 FROM messages WHERE id=$1 AND channel_id=$2',[body.replyTo,id]);if(!rowCount)return reply.code(400).send({error:'Reply must refer to this channel'});}const {rows:[message]}=await db.query('INSERT INTO messages(id,channel_id,author_id,content,nonce,reply_to) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(author_id,nonce) DO NOTHING RETURNING *',[ids.next(),id,req.userId,body.content,body.nonce,body.replyTo??null]);if(!message){const {rows:[existing]}=await db.query('SELECT * FROM messages WHERE author_id=$1 AND nonce=$2 AND channel_id=$3',[req.userId,body.nonce,id]);if(!existing)return reply.code(409).send({error:'Nonce already used'});return existing;}await publish('message.create',id,message);return reply.code(201).send(message);});
app.patch('/channels/:channelId/messages/:messageId',async(req,reply)=>{const id=params(req.params,'channelId'),messageId=params(req.params,'messageId'),body=editMessageSchema.parse(req.body);await requireChannel(req.userId,id,Permission.SEND_MESSAGES);const {rows:[message]}=await db.query('UPDATE messages SET content=$1,edited_at=now() WHERE id=$2 AND channel_id=$3 AND author_id=$4 RETURNING *',[body.content,messageId,id,req.userId]);if(!message)return reply.code(404).send({error:'Message not found'});await publish('message.update',id,message);return message;});
app.delete('/channels/:channelId/messages/:messageId',async(req,reply)=>{const id=params(req.params,'channelId'),messageId=params(req.params,'messageId');const {bits}=await requireChannel(req.userId,id);const {rowCount}=await db.query('DELETE FROM messages WHERE id=$1 AND channel_id=$2 AND (author_id=$3 OR $4)',[messageId,id,req.userId,hasPermission(bits,Permission.MANAGE_MESSAGES)]);if(!rowCount)return reply.code(404).send({error:'Message not found'});await publish('message.delete',id,{id:messageId,channel_id:id});return reply.code(204).send();});
app.post('/channels/:channelId/typing',async(req)=>{const id=params(req.params,'channelId');await requireChannel(req.userId,id,Permission.SEND_MESSAGES);await publish('typing.start',id,{userId:req.userId,expiresAt:Date.now()+8000});return {ok:true};});
app.put('/channels/:channelId/read-state',async(req,reply)=>{const id=params(req.params,'channelId');await requireChannel(req.userId,id);const body=z.object({messageId:snowflakeSchema}).parse(req.body);const {rowCount}=await db.query('SELECT 1 FROM messages WHERE id=$1 AND channel_id=$2',[body.messageId,id]);if(!rowCount)return reply.code(400).send({error:'Message not in channel'});await db.query('INSERT INTO read_states(user_id,channel_id,last_read_message_id) VALUES($1,$2,$3) ON CONFLICT(user_id,channel_id) DO UPDATE SET last_read_message_id=GREATEST(read_states.last_read_message_id,EXCLUDED.last_read_message_id),mention_count=0',[req.userId,id,body.messageId]);return {ok:true};});
app.get('/channels/:channelId/search',async(req)=>{const id=params(req.params,'channelId');await requireChannel(req.userId,id);const {q}=z.object({q:z.string().trim().min(2).max(200)}).parse(req.query);return (await db.query("SELECT id,channel_id,author_id,content,created_at FROM messages WHERE channel_id=$1 AND to_tsvector('english',content) @@ plainto_tsquery('english',$2) ORDER BY id DESC LIMIT 50",[id,q])).rows;});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>void app.close().then(async()=>{await db.end();redis.disconnect();process.exit(0);}));
await app.listen({port:Number(process.env.API_PORT??3001),host:process.env.HOST??'127.0.0.1'});

